version: '3.8'

services:
  backend:
    image: backend-image
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Bind mount para desenvolvimento
      - uploads:/app/uploads  # Volume para persistência de arquivos
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - docker-react_postgres_data:/var/lib/postgresql/data  # Usa o volume existente

  redis:
    image: redis:6
    volumes:
      - docker-react_redis_data:/data

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  docker-react_postgres_data:  # Volume existente para o PostgreSQL
    external: true
  docker-react_redis_data:     # Volume existente para o Redis
    external: true
  uploads: 